#!/bin/sh
# Dockerfile entry point, runs the non-interactive user-dependent stuff

set -ex

[[ $# -lt 2 ]] && {
    cat <<EOF 1>&2
Usage: $(basename $0) STAFF_ID [GIT_URL ...]
EOF
    exit 2
}

user=$1
shift
git_urls="$@"

# Create user
adduser -D -h /home/$user -s /bin/bash $user && \
    ( echo "$user:pass" | chpasswd )
sed -i "s/^\(wheel:.*\)$/\1,$user/" /etc/group
echo $user >> /etc/at.allow

su $user -c "/pod/user-init $git_urls"

node . --base /
