#!/bin/bash
# Encrypts ~/.pod/secrets into ~/.pod/secrets.gpg and back

set -e

SECRETS=.pod/secrets
ARCHIVE=$SECRETS.gpg
export GPG_TTY=$(tty)
cd

([[ -f .gitignore ]] && grep -q "^/.pod/$" ~/.gitignore) || {
    echo "$0: /.pod/ not in .gitignore" 1>&2
    exit 1
}

case $1 in
encrypt) 
    [[ -d $SECRETS ]] || {
        echo "$0: Missing secrets directory $SECRETS" 1>&2
        exit 1
    }
    rm -f $ARCHIVE
    cd $(dirname $SECRETS)   
    tar cfz - $(basename $SECRETS) | gpg -c --cipher-algo aes256 -o $ARCHIVE
    ;;
decrypt) 
    rm -rf $SECRETS
    mkdir -p ~/.pod
    cd $(dirname $SECRETS)
    gpg -d --cipher-algo aes256 $ARCHIVE | tar xfz -
    chmod -R go-rwx $SECRETS
    ;;
status)
    [[ -d $SECRETS ]] && {
        latest=$(find $SECRETS -type f | xargs ls -t | head -1)
        [[ ! -z "$latest" &&  $latest -nt $ARCHIVE ]] && echo "uncommitted secrets"
    }
    ;;
*)
    echo "Usage: pod secrets (encrypt|decrypt|status)" 1>&2
    exit 2
    ;;
esac
